backend:
  name: github
  repo: roman7501/blog_gastby

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Article
    folder: blog
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
